spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_service
    username: auth_user
    password: auth_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
